"use client";
import {useEffect,useMemo,useState} from "react";
type Test={slug:string;name:string;short:string;icon:string;color:string;questionCount:number;duration:number;category:"systems"|"basic"|"grand"};
type Attempt={testSlug:string;status:string;score:number|null;total:number};
type Q={id:number;question:string;options:string[];answer?:number;explanation?:string;selected?:number|null;isCorrect?:boolean};
type FB={selected:number;correctIndex:number;correct:boolean;explanation:string};
const API="/api/portal";
export default function Home(){
 const[view,setView]=useState("loading"),[student,setStudent]=useState<any>(null),[tests,setTests]=useState<Test[]>([]),[attempts,setAttempts]=useState<Attempt[]>([]),[error,setError]=useState("");
 const[login,setLogin]=useState({studentId:"",accessCode:""}),[active,setActive]=useState<Test|null>(null),[questions,setQuestions]=useState<Q[]>([]),[current,setCurrent]=useState(0),[feedback,setFeedback]=useState<Record<number,FB>>({}),[busy,setBusy]=useState(false),[category,setCategory]=useState<"systems"|"basic"|"grand"|null>(null);
 const[adminKey,setAdminKey]=useState(""),[adminData,setAdminData]=useState<any>(null),[newStudent,setNewStudent]=useState({name:"",studentId:"",accessCode:""});
 const attemptMap=useMemo(()=>new Map(attempts.map(x=>[x.testSlug,x])),[attempts]),answered=Object.keys(feedback).length,score=Object.values(feedback).filter(x=>x.correct).length;
 async function boot(){const r=await fetch(API+"?action=session",{cache:"no-store"}),d=await r.json();setTests(d.tests||[]);if(d.authenticated){setStudent(d.student);setAttempts(d.attempts||[]);setView("dashboard")}else setView("login")}
 useEffect(()=>{boot()},[]);
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"login",...login})}),d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);boot()}
 async function signOut(){await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});setStudent(null);setView("login")}
 async function openTest(t:Test){setBusy(true);setError("");const r=await fetch(API+"?action=test&slug="+t.slug,{cache:"no-store"}),d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setActive(t);setQuestions(d.questions);const f:Record<number,FB>={};for(const x of d.saved||[])f[x.questionId]={selected:x.selected,correctIndex:-1,correct:Boolean(x.correct),explanation:"Saved answer. Full explanation is available after final submission."};setFeedback(f);setCurrent(Math.min((d.saved||[]).length,Math.max(0,d.questions.length-1)));setView("quiz");scrollTo(0,0)}
 async function answer(i:number){if(!active||feedback[questions[current].id]||busy)return;setBusy(true);const q=questions[current],r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"answer",slug:active.slug,questionId:q.id,selected:i})}),d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setFeedback(x=>({...x,[q.id]:{selected:i,correctIndex:d.correctIndex,correct:d.correct,explanation:d.explanation}}))}
 async function submit(){if(!active)return;setBusy(true);const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"submit",slug:active.slug})}),d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);openResult(active)}
 async function openResult(t:Test){const r=await fetch(API+"?action=result&slug="+t.slug,{cache:"no-store"}),d=await r.json();if(!r.ok)return setError(d.error);setActive(t);setQuestions(d.questions);setView("result");scrollTo(0,0)}
 async function adminLoad(key=adminKey){const r=await fetch(API+"?action=admin",{headers:{"x-admin-key":key},cache:"no-store"}),d=await r.json();if(!r.ok)return setError(d.error);setAdminData(d);setAdminKey(key);setView("admin")}
 async function createStudent(e:React.FormEvent){e.preventDefault();const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json","x-admin-key":adminKey},body:JSON.stringify({action:"adminCreateStudent",...newStudent})}),d=await r.json();if(!r.ok)return setError(d.error);setNewStudent({name:"",studentId:"",accessCode:""});adminLoad()}
 async function removeStudent(studentId:string){if(!confirm("Remove this student and all saved attempts/results?"))return;const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json","x-admin-key":adminKey},body:JSON.stringify({action:"adminRemoveStudent",studentId})}),d=await r.json();if(!r.ok)return setError(d.error);adminLoad()}
 if(view==="loading")return <main className="loading"><div className="loader"/><b>Preparing NLE Portal…</b></main>;
 if(view==="login")return <main className="authPage"><section className="brandPanel"><img className="doctorPortrait" src="/dr-muhammad-waleed.png" alt="Dr. Muhammad Waleed Saif"/><div className="brand"><span>MW</span><div><b>NLE Test Preparation Portal</b><small>Pakistan · Clinical Mock Examination Series</small></div></div><div className="brandCopy"><p>COMPLETE NLE PREPARATION</p><h1>Learn smarter.<br/><em>Perform better.</em></h1><span>System-wise, basic-subject and full-length Grand Mock assessments with instant explanations and saved results.</span><div className="systemPills"><i>System-wise Tests</i><i>Basic Subjects</i><i>Grand Mock Tests</i><i>Instant Explanations</i></div><aside className="conductorCard"><div className="doctorMark">MW</div><div><small>TEST SERIES CONDUCTED BY</small><strong>Dr. Muhammad Waleed Saif, MBBS</strong><span>Academic supervision · NLE-focused clinical assessment</span></div></aside></div><div className="brandStats"><div><b>3,790</b> High-yield MCQs</div><div><b>3</b> Test categories</div><div><b>1</b> Secure attempt/test</div></div></section><section className="loginPanel"><form onSubmit={signIn}><p className="kicker">SECURE STUDENT ACCESS</p><h2>Begin your assessment</h2><p className="muted">Enter the Student ID and private access code issued for you. Each test can be attempted once; answers are saved and results remain available afterward.</p><div className="loginNotice"><b>Before you begin</b><span>Choose carefully—each selection is locked immediately and its correct answer with explanation appears on screen.</span></div><label>Student ID<input value={login.studentId} onChange={e=>setLogin({...login,studentId:e.target.value})} placeholder="e.g. NLE-001" autoComplete="username"/></label><label>Private access code<input type="password" value={login.accessCode} onChange={e=>setLogin({...login,accessCode:e.target.value})} placeholder="Enter your private code" autoComplete="current-password"/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Verifying access…":"Enter NLE portal →"}</button><button type="button" className="adminLink" onClick={()=>{const k=prompt("Teacher admin code");if(k)adminLoad(k)}}>Dr. Muhammad Waleed / Teacher dashboard</button></form></section></main>;
 if(view==="admin")return <main className="portal"><Top title="Teacher Dashboard" subtitle="Dr. Muhammad Waleed Saif, MBBS" exit={()=>setView("login")}/><section className="welcome"><div><p className="kicker">ADMIN CONTROL</p><h1>Students & Results</h1><p className="muted">Create student access and monitor one-time attempts.</p></div><div className="progressRing"><b>{adminData?.students?.length||0}</b><span>Students</span></div></section><div className="adminGrid"><form className="panel" onSubmit={createStudent}><h2>Add student</h2><label>Full name<input value={newStudent.name} onChange={e=>setNewStudent({...newStudent,name:e.target.value})}/></label><label>Student ID<input value={newStudent.studentId} onChange={e=>setNewStudent({...newStudent,studentId:e.target.value})}/></label><label>Private code<input value={newStudent.accessCode} onChange={e=>setNewStudent({...newStudent,accessCode:e.target.value})}/></label>{error&&<div className="error">{error}</div>}<button>Create access</button></form><section className="panel tablePanel studentPanel"><h2>Student access</h2><table><thead><tr><th>Student</th><th>Login</th><th>Action</th></tr></thead><tbody>{(adminData?.students||[]).map((s:any)=><tr key={s.studentId}><td><b>{s.name}</b><small>{s.studentId}</small></td><td><span className={"badge "+(s.loggedIn?"completed":"")}>{s.loggedIn?"Logged in":"Offline"}</span></td><td><button className="dangerBtn" onClick={()=>removeStudent(s.studentId)}>Remove</button></td></tr>)}</tbody></table>{!adminData?.students?.length&&<div className="empty">No students added yet.</div>}</section><section className="panel tablePanel resultsPanel"><h2>Recorded attempts</h2><table><thead><tr><th>Student</th><th>Test</th><th>Status</th><th>Score</th></tr></thead><tbody>{(adminData?.results||[]).map((x:any,i:number)=><tr key={i}><td><b>{x.name}</b><small>{x.studentId}</small></td><td>{tests.find(t=>t.slug===x.testSlug)?.short||x.testSlug}</td><td><span className={"badge "+x.status}>{x.status}</span></td><td>{x.score==null?"—":x.score+"/"+x.total}</td></tr>)}</tbody></table>{!adminData?.results?.length&&<div className="empty">No attempts recorded yet.</div>}</section></div></main>;
 if(view==="dashboard")return <main className="portal"><Top title="NLE Test Portal" subtitle={student.name+" · "+student.studentId} exit={signOut}/><section className="welcome"><div><p className="kicker">STUDENT DASHBOARD</p><h1>{category?category==="systems"?"System-wise Tests":category==="basic"?"Basic Subject Tests":"Grand Mock Tests":"Choose your preparation track"}</h1><p className="muted">Each test can be attempted once. Progress saves automatically and completed results remain available.</p>{category&&<button className="outline categoryBack" onClick={()=>setCategory(null)}>← Back to categories</button>}</div><div className="progressRing"><b>{attempts.filter(x=>x.status==="completed").length}</b><span>Completed</span></div></section>{error&&<div className="error wide">{error}</div>}{!category?<section className="categoryGrid">
<button className="categoryCard systemsCategory" onClick={()=>setCategory("systems")}><span>⚕</span><small>NLE CLINICAL PREPARATION</small><h2>System-wise Tests</h2><p>CVS, GIT, Respiratory, Endocrinology, Renal, Neurology, Rheumatology, Reproductive and Hematology.</p><b>Explore 9 systems →</b></button>
<button className="categoryCard basicCategory" onClick={()=>setCategory("basic")}><span>⌬</span><small>FOUNDATION SCIENCES</small><h2>Basic Subject Tests</h2><p>Immunology, Biochemistry, Microbiology, Anatomy, Physiology, General Pathology, Community/Family Medicine and Pharmacology.</p><b>Explore basic subjects →</b></button>
<button className="categoryCard grandCategory" onClick={()=>setCategory("grand")}><span>★</span><small>FULL-LENGTH NLE SIMULATION</small><h2>Grand Mock Tests</h2><p>Ten complete 200-MCQ examinations for full NLE practice without subject labels during the test.</p><b>Explore 10 Grand Mocks →</b></button>
</section>:<section className={"systems "+(category==="grand"?"grandTests":"")}>{tests.filter(t=>t.category===category).map(t=>{const a=attemptMap.get(t.slug);return <article className={"systemCard "+(category==="basic"?"basicSubject":category==="grand"?"grandTest":"")} key={t.slug} style={{"--accent":t.color} as React.CSSProperties}><div className="systemIcon">{t.icon}</div><div className="cardTop"><span>{t.short}</span><span className={"status "+(a?.status||"new")}>{a?.status==="completed"?"Completed":a?.status==="in_progress"?"In progress":"Not attempted"}</span></div><h2>{t.name}</h2><p>{category==="grand"?`${t.questionCount} integrated NLE MCQs · 3-hour full exam`:category==="systems"?`${t.questionCount} clinical and conceptual MCQs · Instant explanations`:`${t.questionCount} high-yield NLE MCQs · Instant explanations`}</p><div className="cardMeta"><span>◷ {t.duration} min</span><span>◆ {t.questionCount} marks</span></div>{a?.status==="completed"?<button className="outline" onClick={()=>openResult(t)}>View result</button>:<button disabled={busy} onClick={()=>openTest(t)}>{a?.status==="in_progress"?"Continue test":"Start one-time test"}</button>}</article>})}</section>}</main>;
 if(view==="result"&&active){const correct=questions.filter(q=>q.isCorrect).length,pct=Math.round(correct/questions.length*100);return <main className="portal"><Top title={active.name+" Result"} subtitle={student.name} exit={()=>boot()}/><section className="resultHero"><div className="scoreCircle" style={{background:"conic-gradient("+active.color+" "+pct+"%,#e5eeee 0)"}}><div><b>{pct}%</b><span>{correct}/{questions.length}</span></div></div><div><p className="kicker">COMPLETED · ATTEMPT LOCKED</p><h1>{active.name}</h1><p className="muted">Your full answer review is permanently available.</p></div></section><section className="review">{questions.map(q=><article className={"reviewQ "+(q.isCorrect?"good":"bad")} key={q.id}><header><b>Q{q.id}</b><span>{q.isCorrect?"✓ Correct":"✕ Incorrect"}</span></header><h3>{q.question}</h3>{q.options.map((o,i)=><div className={"reviewOption "+(i===q.answer?"correct ":"")+(i===q.selected&&i!==q.answer?"selectedWrong":"")} key={o}><b>{String.fromCharCode(65+i)}</b>{o}</div>)}<p><b>Explanation:</b> {q.explanation}</p></article>)}</section></main>}
 const q=questions[current],f=q&&feedback[q.id];return <main className="quizPage"><header className="quizHeader"><button className="back" onClick={()=>setView("dashboard")}>← Dashboard</button><div><b>{active?.name}</b><span>{student.name}</span></div><div className="liveScore">Score <b>{score}/{answered}</b></div></header><div className="quizProgress"><div><span>Question {current+1} of {questions.length}</span><span>{Math.round(answered/questions.length*100)}% answered</span></div><i><b style={{width:Math.round(answered/questions.length*100)+"%"}}/></i></div>{error&&<div className="error wide">{error}</div>}<section className="question"><div className="qTag">QUESTION {q.id}</div><h1>{q.question}</h1><div className="options">{q.options.map((o,i)=>{let c="option";if(f){if(i===f.correctIndex)c+=" correct";else if(i===f.selected)c+=" wrong";else c+=" locked"}return <button className={c} onClick={()=>answer(i)} disabled={Boolean(f)||busy} key={o}><span>{String.fromCharCode(65+i)}</span><b>{o}</b>{f&&i===f.correctIndex?<em>✓</em>:f&&i===f.selected?<em>×</em>:null}</button>})}</div>{f&&<div className={"feedback "+(f.correct?"good":"bad")}><h3>{f.correct?"✓ Correct answer":"✕ Incorrect answer"}</h3>{!f.correct&&f.correctIndex>=0&&<b>Correct: {String.fromCharCode(65+f.correctIndex)}. {q.options[f.correctIndex]}</b>}<p>{f.explanation}</p></div>}<nav><button className="outline" disabled={current===0} onClick={()=>setCurrent(current-1)}>Previous</button>{current<questions.length-1?<button disabled={!f} onClick={()=>setCurrent(current+1)}>Next question →</button>:<button disabled={answered<questions.length||busy} onClick={submit}>Submit final test</button>}</nav></section><div className="navigator">{questions.map((x,i)=><button key={x.id} className={(current===i?"active ":"")+(feedback[x.id]?"done":"")} onClick={()=>setCurrent(i)}>{x.id}</button>)}</div></main>
}
function Top({title,subtitle,exit}:{title:string;subtitle:string;exit:()=>void}){return <header className="topbar"><div className="logo">MW</div><div><b>{title}</b><span>{subtitle}</span></div><button className="outline" onClick={exit}>Exit</button></header>}
